[profile.default]
src = 'src'
out = 'out'
libs = ['lib',"node_modules"]
optimizer = false

remappings = [
    'forge-std/=lib/forge-std/src/',
    '@zondax/filecoin-solidity/=lib/filecoin-solidity/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'solidity-cborutils/=lib/filecoin-solidity/lib/solidity-cborutils/contracts/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config