[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = false

remappings = [
    'forge-std/=lib/forge-std/src/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    '@zondax/filecoin-solidity/=lib/filecoin-solidity/',
    'solidity-cborutils/=lib/filecoin-solidity/lib/solidity-cborutils/contracts/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config