[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'buffer/=lib/buffer/contracts/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/',
    'filecoin-solidity/=lib/filecoin-solidity/',
    'forge-std/=lib/forge-std/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    'solidity-cborutils/=lib/solidity-cborutils/contracts/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config